---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: weather-backend-05
  namespace: rma010101-dev
  labels:
    app: weather-backend-05
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: weather-backend-05
  namespace: rma010101-dev
  labels:
    app: weather-backend-05
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/rma010101/rev15-weather-backend-005.git"
      ref: main
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: "weather-backend-05:latest"
  triggers:
    - type: GitHub
      github:
        secret: "secret101"
    - type: Generic
      generic:
        secret: "secret101"
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend-05
  namespace: rma010101-dev
  labels:
    app: weather-backend-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-backend-05
  template:
    metadata:
      labels:
        app: weather-backend-05
    spec:
      containers:
        - name: weather-backend-05
          image: image-registry.openshift-image-registry.svc:5000/rma010101-dev/weather-backend-05:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openweathermap-api-key-5
                  key: OPENWEATHER_API_KEY
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: weather-backend-05
  namespace: rma010101-dev
  labels:
    app: weather-backend-05
spec:
  selector:
    app: weather-backend-05
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: weather-backend-05-route
  namespace: rma010101-dev
  labels:
    app: weather-backend-05
spec:
  to:
    kind: Service
    name: weather-backend-05
  port:
    targetPort: http
  tls:
    termination: edge
